### PR TITLE
fix: use helm version --client

### PR DESCRIPTION
**Pull request by teejaded**
Fix for issue #1

### CODE REVIEW

**Comment by mike10010100** [comment]
@davidnewman can this be merged? I'm running into the same issue and would really like to use this cookbook.

**Comment by davidnewman** [comment]
Sorry about that! It's merged now.

**Comment by mike10010100** [comment]
@davidnewman Thank you so much! Would it be possible to get this pushed to the supermarket? Thanks again!

**Comment by davidnewman** [comment]
@mike10010100 All set!

**Comment by mike10010100** [comment]
@davidnewman Thank you once again!!! 😄

**Pull request merged**
